# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: BSPL is..
    url: "/aims"
    weight: 10
  - name: Members
    url: "/members"
    weight: 20
  - name: Publications
    identifier: "publications"
    weight: 30

  - name: "Articles"
    url: "/publications/articles"
    weight: 1
    parent: "publications"
  - name: "Domestic Conferences"
    url: "/publications/domestic_conferences"
    weight: 2
    parent: "publications"
  - name: "International Conferences"
    url: "/publications/international_conferences"
    weight: 3
    parent: "publications"

  - name: Softwares
    identifier: "softwares"
    weight: 40

  - name: DNN
    url: "/softwares/dnn"
    weight: 1
    parent: "softwares"
  - name: iDR
    url: "/softwares/idr"
    weight: 2
    parent: "softwares"
  - name: rsPCA
    url: "/softwares/rspca"
    weight: 3
    parent: "softwares"
  - name: ENV
    url: "/softwares/env"
    weight: 4
    parent: "softwares"

  - name: Interesting Works
    url: "/interesting_works"
    weight: 50
  - name: Lab News
    url: "/news"
    weight: 60
  - name: Contact Us
    url: "/contact"
    weight: 70
# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/uploads/resume.pdf` and uncomment the lines below.
#  - name: CV
#    url: uploads/resume.pdf
#    weight: 70
